enum NodeType {
    ELEMENT_NODE = Node.ELEMENT_NODE,
    ATTRIBUTE_NODE = Node.ATTRIBUTE_NODE,
    TEXT_NODE = Node.TEXT_NODE,
    CDATA_SECTION_NODE = Node.CDATA_SECTION_NODE,
    ENTITY_REFERENCE_NODE = Node.ENTITY_REFERENCE_NODE,
    ENTITY_NODE = Node.ENTITY_NODE,
    PROCESSING_INSTRUCTION_NODE = Node.PROCESSING_INSTRUCTION_NODE,
    COMMENT_NODE = Node.COMMENT_NODE,
    DOCUMENT_NODE = Node.DOCUMENT_NODE,
    DOCUMENT_TYPE_NODE = Node.DOCUMENT_TYPE_NODE,
    DOCUMENT_FRAGMENT_NODE = Node.DOCUMENT_FRAGMENT_NODE,
    NOTATION_NODE = Node.NOTATION_NODE
}
